server:
  port: 8080
  servlet:
    context-path: /
spring:
  data:
    mongodb:
      uri: mongodb+srv://${databaseUser}:${databasePassword}@booklounge.b754vyg.mongodb.net/?tls=true
      database: BookLounge
      username: ${databaseUser}
      password: ${databasePassword}
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  security:
    jwt:
      secret: 327235753878214125442A472D4B6150645367566B597033733676397924423F4528482B4D6251655468576D5A7134743777217A25432A46294A404E63526655
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    host: smtp.gmail.com
    username: ${email}
    password: ${emailPassword}
    port: '587'
  aws:
   accessKey: ${AwsAccessKey}
   secretKey: ${AwsSecretKey}
   region: eu-north-1
   bucketName: book-lounge-storage