server:
  port: 8080
  servlet:
    context-path: /
spring:
  config:
    import: aws-secretsmanager:BookLounge
  data:
    mongodb:
      uri: mongodb+srv://${databaseUser}:${databasePassword}@booklounge.b754vyg.mongodb.net/?tls=true
      database: BookLounge
    security:
      jwtKey: ${jwtSecret}
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    host: smtp.gmail.com
    username: ${email}
    password: ${emailPassword}
    port: '587'
  aws:
    accessKey: ${AwsAccessKey}
    secretKey: ${AwsSecretKey}
    region: eu-north-1
    bucketName: book-lounge-storage
